name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: nexploretestdeploy.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build and push to ${{ github.sha }}
        id: docker_build_github_sha
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nexploretestdeploy.azurecr.io/nodejs-helloworld:${{ github.sha }}
      - name: Build and push to ${{ secrets.VERSION_TAG }}
        id: docker_build_version_tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nexploretestdeploy.azurecr.io/nodejs-helloworld:${{ secrets.VERSION_TAG }}
      - name: Image digest with docker_build_github_sha
        run: echo ${{ steps.docker_build_github_sha.outputs.digest }}
      - name: Image digest with docker_build_version_tag
        run: echo ${{ steps.docker_build_version_tag.outputs.digest }}
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: nodejs-helloworld
          slot-name: dev
          images: nexploretestdeploy.azurecr.io/nodejs-helloworld:${{ secrets.VERSION_TAG }}
      - name: Sign out of Azure
        run: |
          az logout
